version: "3"

vars:
  XDG_DATA_HOME: "{{.HOME}}/.local/share"

env:
  DATABASE_URL: "file:{{.XDG_DATA_HOME}}/lanventory/lanventory.sqlite"
  DB_AUTH_TOKEN: IF_USING_TURSO
  HOST_NAME: "http://localhost:3000"

tasks:
  init:
    silent: true
    cmds:
      - bun install
      # Dump some environment variables to a nodejs friendly .env file TODO: Copy sample to .config/lanventory/.env and then configure with defaults per env
      - |
        cat <<'EOF' > .env
        DATABASE_URL={{.DATABASE_URL}}
        DB_AUTH_TOKEN={{.DB_AUTH_TOKEN}}
        HOST_NAME={{.HOST_NAME}}
        EOF
      - cmd: mkdir -p {{.XDG_DATA_HOME}}/lanventory
    sources:
      - node_modules
    generates:
      - bun.lock

  run:
    desc: "Run the test application for lanventory"
    deps:
      - init
    cmds:
      - bun run dev

  drizzle-gen:
    desc: "Generate the database schema"
    deps:
      - init
    cmds:
      - bunx drizzle-kit generate --config="drizzle.config.ts"

  drizzle-sync:
    desc: "Sync the database with the latest schema"
    deps:
      - init
    cmds:
      - bunx drizzle-kit push --config="drizzle.config.ts"

  drizzle-studio:
    desc: "Open the database studio"
    deps:
      - init
    cmds:
      - bunx drizzle-kit studio --config="drizzle.config.ts"

  drizzle-reset:
    desc: "Reset the database"
    deps:
      - init
    cmds:
      - bunx drizzle-kit reset --config="drizzle.config.ts"

  tools:nmap:
    desc: "Install nmap"
    status:
      - $(command -v nmap) || brew install nmap
    deps:
      - init
    cmds:
      - bun run src/bin/main.ts nmap 192.168.2.0/24 /tmp/ip-range.xml
